### ISSUE TITLE
Feature request: multiple data requirements in json file?

### ISSUE THREAD

**Issue by mathieuboudreau** [SIMEXP/Repo2Data#1]
Is this already possible? I haven't been able to find a way to do so. e.g. if I have multiple data files to download, I'd prefer to keep them all in the same data file instead of having multiple *.json file.

I imaging it should handle a json that somewhat look like:

```json
{
  "inversion_recovery": {
    "src": "https://osf.io/ezv74/download/",
    "dst": "./",
    "projectName": "ir_dataset",
    "recursive": true
  },
  "vfa": {
    "src": "https://osf.io/wj6eg/download/",
    "dst": "./",
    "projectName": "vfa_dataset",
    "recursive": true
  }
}
```

**Comment by mathieuboudreau** [comment]
And then, maybe have a CLI flag that lets you select only one of those in that file to download. 

e.g. `repo2data -r ir_dataset.json -s inversion_recovery`

**Comment by ltetrel** [comment]
It is not yet possible, but it would be a nice improvement !
Is it for the osf data ?

**Comment by ltetrel** [comment]
We would need a mechanism to detect that there is indeed multiple fields to download them one by one.. I will look into it,

**Comment by mathieuboudreau** [comment]
>It is not yet possible, but it would be a nice improvement !
Is it for the osf data ?

Yeah, for my application, my files are split up in different OSF zips. I just thought it might be a good functionality to have in general, since other people might have similar situations. It would be cleaner than to call repo2data multiple times in a Dockerfile (e.g. my application), and simpler than writing a shell script like I did:

https://github.com/qMRLab/t1_book/blob/31831886d9873f16840305d0bffabbdef3398d04/Dockerfile#L75

**Comment by ltetrel** [comment]
@mathieuboudreau the feature should work now, can you try it on [this branch](https://github.com/SIMEXP/Repo2Data/tree/multiple_data_requirement) before I merge it?

**Comment by mathieuboudreau** [comment]
@ltetrel works great for me on my end (MacOS 10.14.3, pip 18.1, python 3.7) ! Thanks a lot!
