### ISSUE TITLE
document python API

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/Repo2Data#16]
Unless I missed something, I cannot find documentation for https://github.com/SIMEXP/Repo2Data/blob/master/repo2data/repo2data.py and the code itself has no docstrings.

**Comment by ltetrel** [comment]
I think this commit https://github.com/SIMEXP/Repo2Data/commit/8a26b13e3629ce7fc1e0d7cec03d822adbc0e1b5 should do the job:
https://github.com/SIMEXP/Repo2Data#execution
