### ISSUE TITLE
OSF fetch directives for subset data

### ISSUE THREAD

**Issue by agahkarakuzu** [SIMEXP/Repo2Data#17]
Right now, when osf link is detected, `repo2data` attempts `osf clone`. This works when cloning a whole [project](https://osf.io/6zbyf/), but fails when an osf link associated with [individual data](https://osf.io/kjcgs/) in a project. 

Failing config: 

```json
{ "src": "https://osf.io/kjgcs",
  "dst": "./data",
  "projectName": "repo2data_osf",
  "recursive": true}
```

The osf command that works for what user requests:

```terminal
osf -p 6zbyf fetch data/20160918_sct_example_data.zip ./data/20160918_sct_example_data.zip
```

For subsets of a project, `data_requirement.json` can be something like:

```json
{ "src": "https://osf.io/6zbyf ",
   "remotePath": "data/20160918_sct_example_data.zip",
  "dst": "./data",
  "projectName": "repo2data_osf",
  "recursive": true}
```

Something like this, or something you see fit. We should document that in case of `osf`,  the `src` MUST be the link containing the project id. If a subset needed, `remotePath` should be provided.

**Comment by ltetrel** [comment]
@jvelazquez-reyes @agahkarakuzu
https://github.com/SIMEXP/Repo2Data#osf

I will ping you when this release will be available on Neurolibre, still need to update things on the cluster.
